#!/usr/bin/env python3
"""Regenerate macos/SyphonMetalShadersEmbedded.h from the vendored Syphon shader.

Run from native/frameshare/: python3 scripts/generate-embedded-shader.py
Only needed when the vendored SyphonMetalShaders.metal or
SyphonServerMetalTypes.h change.
"""
import os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
v = os.path.join(root, 'vendor', 'syphon')
types = open(os.path.join(v, 'SyphonServerMetalTypes.h')).read()
metal = open(os.path.join(v, 'SyphonMetalShaders.metal')).read()
metal = metal.replace('#include "SyphonServerMetalTypes.h"',
                      '/* SyphonServerMetalTypes.h inlined above */')
data = (types + '\n' + metal).encode('utf-8') + b'\0'
lines = [', '.join(f'0x{b:02x}' for b in data[i:i + 16]) for i in range(0, len(data), 16)]
body = ',\n    '.join(lines)
out = f"""/*
 SyphonMetalShadersEmbedded.h — generated file, do not edit by hand.

 Generated by native/frameshare/scripts/generate-embedded-shader.py from
 vendor/syphon/SyphonServerMetalTypes.h and vendor/syphon/SyphonMetalShaders.metal
 (Syphon-Framework, BSD-2 license — see vendor/syphon/License.txt).

 Figment statically links Syphon, so there is no framework bundle carrying a
 compiled default.metallib. The patched SyphonServerRendererMetal.m compiles
 this source at runtime with -[MTLDevice newLibraryWithSource:] instead.
*/

static const char kSyphonEmbeddedMetalShaderSource[] = {{
    {body}
}};
"""
open(os.path.join(root, 'macos', 'SyphonMetalShadersEmbedded.h'), 'w').write(out)
print('wrote', len(data), 'bytes')
